// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12-hS_LGAkFTk9AXeJR2avHUvRDZ_9ho',
    appId: '1:205710084419:android:a768e2ca1f538c3a7947f6',
    messagingSenderId: '205710084419',
    projectId: 'surge-monitor',
    databaseURL: 'https://surge-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'surge-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwC1s8rCyOrbyShLII8zPHh57yLIJcz5E',
    appId: '1:205710084419:ios:5cc3be795eb70f1f7947f6',
    messagingSenderId: '205710084419',
    projectId: 'surge-monitor',
    databaseURL: 'https://surge-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'surge-monitor.firebasestorage.app',
    iosClientId: '205710084419-f8n4dr36cj31ev4v5thorvqf0u5ga5rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.surgeMonitor',
  );
}
